spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://CLIENT-MICROSERVICE
            predicates:
              - Path=/api/customers/**

          - id: r2
            uri: lb://PRODUCT-MICROSERVICE
            predicates:
              - Path=/api/products/**
